//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Design_Dashboard_Modern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id { get; set; }
        public string cuit { get; set; }
        public string NombreyApellido { get; set; }
        public string DNI { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string direccion { get; set; }
        public string numeroTelefono { get; set; }
        public string email { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<double> porcentajeRentabilidad { get; set; }
    }
}
