//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Design_Dashboard_Modern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public int ComprobanteId { get; set; }
        public string codigo { get; set; }
        public double importe { get; set; }
        public double bonificacion { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public int ClienteId { get; set; }
        public int TipoComprobanteId { get; set; }
        public int SucursalId { get; set; }
        public double efectivo { get; set; }
        public double tarjeta { get; set; }
        public string UserName { get; set; }
        public Nullable<double> Tarjeta1 { get; set; }
        public Nullable<double> Tarjeta2 { get; set; }
        public Nullable<double> TarjDebito { get; set; }
        public Nullable<double> Transferencia { get; set; }
        public Nullable<double> GedNet { get; set; }
        public Nullable<double> Mercadopago { get; set; }
    }
}
